# Generated by Django 5.0.7 on 2024-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ichimliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ichimlik_nomi', models.CharField(max_length=200)),
                ('ichimlik_narxi', models.IntegerField()),
                ('ichimlik_rasmi', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Taomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_nomi', models.CharField(max_length=200)),
                ('taom_narxi', models.IntegerField()),
                ('taom_rasmi', models.ImageField(upload_to='media')),
                ('taom_malumoti', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
